In [55]:
import pandas as pd
import numpy as np

In [62]:
df = pd.read_csv('../Soluciones/MM1c.exe-Size' + str(100) + '-core' + str(1), header = None, sep=":")
df.to_csv('./Soluciones-Ubuntu-2/MM1c-Size' + str(100) + '-core' + str(1), index = False, header = False)

In [58]:
cores = [1, 2, 4, 8, 10, 14, 16, 20]
sizes = [100, 200, 400, 600, 800, 1000, 1500, 2000]

for i in range(len(cores)):
    for j in range(len(sizes)):
        df = pd.read_csv('../Soluciones/MM1c.exe-Size' + str(sizes[j]) + '-core' + str(cores[i]), header = None, sep = ':')
        df.to_csv('../utility/Soluciones-Ubuntu-2/MM1c-Size' + str(sizes[j]) + '-core' + str(cores[i]) + '.csv', index = False, header = False)

In [6]:
df = pd.read_csv('./Soluciones-Ubuntu-2/MM1c-Size' + str(100) + '-core' + str(1) + '.csv', header = None)
df

    0     1
0   0   350
1   0   304
2   0  2897
3   0   309
4   0   316
5   0   313
6   0   313
7   0   309
8   0   311
9   0   301
10  0   300
11  0   318
12  0   313
13  0   332
14  0   313
15  0   313
16  0   319
17  0   323
18  0   312
19  0   321
20  0   291
21  0   298
22  0   732
23  0   304
24  0   370
25  0   288
26  0   291
27  0   305
28  0   294
29  0   283

In [61]:
from csv import writer

cores = [1, 2, 4, 8, 10, 14, 16, 20]
sizes = [100, 200, 400, 600, 800, 1000, 1500, 2000]

for i in range(len(cores)):
    for j in range(len(sizes)):
        df = pd.read_csv('./Soluciones-Ubuntu-2/MM1c-Size' + str(sizes[j]) + '-core' + str(cores[i]) + '.csv', header = None, names = ['core', 'time'])

        df_2 = df.groupby('core', as_index=False)['time'].mean()
        df_2['time'] = df_2['time'].round(2)

        with open('times.csv', 'a') as f_object:
        
            # Pass this file object to csv.writer()
            # and get a writer object
            writer_object = writer(f_object)
        
            # Pass the list as an argument into
            # the writerow()
            for ind in df_2.index:
                writer_object.writerow([cores[i], sizes[j], df_2['core'][ind], df_2['time'][ind]])
        
            # Close the file object
            f_object.close()

In [60]:
df = pd.read_csv('./times.csv')
df.to_csv('./times.csv', index=False)

In [54]:
df = pd.read_csv('./times.csv')
df = df.drop('core', axis=1)
df_2 = df.groupby(['total_cores', 'sizes'], as_index=False)['time'].mean()
df_2['time'] = df_2['time'].round(2)

df_2.to_csv('./times.csv', index=False)